### ISSUE TITLE
invite.me

### ISSUE THREAD

**Issue by Mhassanbughio** [github-craftwork/start-here#242]

**Comment by thuongtruong1009** [comment]
@Mhassanbughio 
Click create a new issue and then follow the template, then an invitation to join the organization will be automatically sent to you.
Thanks!

**Comment by thuongtruong1009** [comment]
Hi @Mhassanbughio 
You should typing **.invite me** at [here](https://github.com/github-craftwork/start-here/issues/100)
Thank you!
