### ISSUE TITLE
Please invite me to the Github Community Organization

### ISSUE THREAD

**Issue by Jyoti-prakash-rout** [github-craftwork/start-here#245]
I'm an Web Dev Enthusiasts & a junior pursuing my Bachelors in Computer Science & Engineering. I'm interested in Web Devlopment, Android Devlopment, IOS Devlpoment, Machine Learning & Devops & I enjoy learning new things & stuff as well as I'm a Frontend Devloper with experience building Dynamic & Static Web pages. I am always interested in learning the answers to how, why and what relating to Technologies around me.

I would like to grow my programming skills by doing lot's of Open Source Contribution. Looking forward to learn, collabrate and grow as a community.

**Comment by thuongtruong1009** [comment]
@Jyoti-prakash-rout 
Congratulations on becoming a full member of this organization.
Please contribute as much as possible to the organization's projects.
Keep the energy forever.
Thank you very much!
