### ISSUE TITLE
.invite me

### ISSUE THREAD

**Issue by IlliaButenko** [github-craftwork/start-here#269]
I'd like to join this organization

**Comment by d-coder111** [comment]
Just type  `.invite me` in comments by clicking on [this issue](https://github.com/github-craftwork/start-here/issues/100).

Once you have submitted your comment, head over to the [Actions tab](https://github.com/github-craftwork/start-here/actions?workflow=Invite+a+contributor) for the the repo to find action triggered by your comment. 

Note that  this could take up to 30 seconds to show. Also be sure to check your email for that invite.
